export const SECTORS = {
  commerce: {
    id: 'commerce',
    nom: 'Commerce & Distribution',
    description: 'Gestion des stocks, ventes, fournisseurs et facturation',
    icon: 'ShoppingCart',
    color: 'brand',
    modules: ['stock', 'ventes', 'fournisseurs', 'clients', 'rapports_commerce'],
  },
  finance: {
    id: 'finance',
    nom: 'Finance & Comptabilité',
    description: 'Comptabilité OHADA, trésorerie, bilans et rapports financiers',
    icon: 'Landmark',
    color: 'emerald',
    modules: ['plan_comptable', 'ecritures', 'journaux', 'grand_livre', 'balance', 'bilan', 'tresorerie', 'creances', 'rapports_finance'],
  },
  industrie: {
    id: 'industrie',
    nom: 'Industrie & Artisanat',
    description: 'Production, matières premières, traçabilité et coûts',
    icon: 'Factory',
    color: 'amber',
    modules: ['matieres_premieres', 'production', 'production_suivi', 'tracabilite', 'couts_marges', 'commandes_production'],
  },
  transport: {
    id: 'transport',
    nom: 'Transport & Logistique',
    description: 'Livraisons, véhicules, chauffeurs et itinéraires',
    icon: 'Truck',
    color: 'sky',
    modules: ['livraisons', 'vehicules', 'chauffeurs', 'colis', 'itineraires', 'couts_logistiques'],
  },
  sante: {
    id: 'sante',
    nom: 'Santé & Pharmacies',
    description: 'Médicaments, patients, ordonnances et assurance',
    icon: 'Heart',
    color: 'rose',
    modules: ['medicaments', 'patients', 'ordonnances', 'assurance', 'consommation'],
  },
  education: {
    id: 'education',
    nom: 'Éducation & Formation',
    description: 'Inscriptions, notes, emplois du temps et pédagogie',
    icon: 'GraduationCap',
    color: 'violet',
    modules: ['inscriptions', 'eleves', 'notes', 'emplois_du_temps', 'enseignants', 'rapports_pedagogiques'],
  },
  ong: {
    id: 'ong',
    nom: 'ONG & Associations',
    description: 'Projets, bénéficiaires, partenaires et rapports',
    icon: 'HandHeart',
    color: 'teal',
    modules: ['projets', 'beneficiaires', 'activites_ong', 'partenaires', 'rapports_ong', 'budget_ong'],
  },
}

export const MODULE_LABELS = {
  stock: 'Stock & Inventaire',
  ventes: 'Ventes & Facturation',
  fournisseurs: 'Fournisseurs',
  clients: 'Clients',
  rapports_commerce: 'Rapports',

  plan_comptable: 'Plan Comptable OHADA',
  ecritures: 'Écritures Comptables',
  journaux: 'Journaux',
  grand_livre: 'Grand Livre',
  balance: 'Balance Générale',
  bilan: 'Bilan & Résultat',
  tresorerie: 'Trésorerie',
  creances: 'Créances & Dettes',
  rapports_finance: 'Rapports Financiers',

  matieres_premieres: 'Matières Premières',
  production: 'Production',
  production_suivi: 'Suivi de Production',
  tracabilite: 'Traçabilité',
  couts_marges: 'Coûts & Marges',
  commandes_production: 'Commandes',

  livraisons: 'Livraisons',
  vehicules: 'Véhicules',
  chauffeurs: 'Chauffeurs',
  colis: 'Colis & Envois',
  itineraires: 'Itinéraires',
  couts_logistiques: 'Coûts Logistiques',

  medicaments: 'Médicaments',
  patients: 'Patients',
  ordonnances: 'Ordonnances',
  assurance: 'Assurance',
  consommation: 'Consommation',

  inscriptions: 'Inscriptions',
  eleves: 'Élèves',
  notes: 'Notes & Bulletins',
  emplois_du_temps: 'Emplois du Temps',
  enseignants: 'Enseignants',
  rapports_pedagogiques: 'Rapports',

  projets: 'Projets',
  beneficiaires: 'Bénéficiaires',
  activites_ong: 'Activités',
  partenaires: 'Partenaires & Donateurs',
  rapports_ong: 'Rapports',
  budget_ong: 'Budget',
}

export const ALL_MODULES = Object.values(SECTORS).flatMap(s => s.modules)
