const { contextBridge, ipcRenderer } = require('electron')

// All DB operations use sendSync for compatibility with synchronous page components
function syncDb(method) {
  return function() {
    return ipcRenderer.sendSync('db:sync', method, ...Array.from(arguments))
  }
}

contextBridge.exposeInMainWorld('electronAPI', {
  getVersion: () => ipcRenderer.invoke('get-app-version'),
  getDataPath: () => ipcRenderer.invoke('get-app-path'),
  getPlatform: () => ipcRenderer.invoke('get-platform'),
  getUserDataPath: () => ipcRenderer.invoke('get-user-data-path'),

  store: {
    get: (key) => ipcRenderer.invoke('store:get', key),
    set: (key, value) => ipcRenderer.invoke('store:set', key, value),
    delete: (key) => ipcRenderer.invoke('store:delete', key),
  },

  window: {
    minimize: () => ipcRenderer.invoke('minimize-window'),
    maximize: () => ipcRenderer.invoke('maximize-window'),
    close: () => ipcRenderer.invoke('close-window'),
    reload: () => ipcRenderer.invoke('app:reload'),
  },

  setMinimizeToTray: (v) => ipcRenderer.invoke('toggle-tray', v),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),

  checkUpdate: () => ipcRenderer.invoke('check-update'),
  downloadUpdate: (url) => ipcRenderer.invoke('download-update', url),
  onUpdateProgress: (cb) => {
    var handler = (_, data) => cb(data)
    ipcRenderer.on('update-progress', handler)
    return () => ipcRenderer.removeListener('update-progress', handler)
  },

  // ── OTP & Messaging ──
  sendOTP: (userId, channel) => ipcRenderer.invoke('otp:send', userId, channel),
  verifyOTP: (userId, code) => ipcRenderer.invoke('otp:verify', userId, code),
  getOTPChannel: (userId) => ipcRenderer.invoke('otp:get-channel', userId),
  configureTwilio: (config) => ipcRenderer.invoke('twilio:config', config),
  testTwilio: (phone) => ipcRenderer.invoke('twilio:test', phone),
  configureSMTP: (config) => ipcRenderer.invoke('smtp:config', config),
  testSMTP: (to) => ipcRenderer.invoke('smtp:test', to),

  // ── Database API (synchronous IPC) ──
  db: {
    isAvailable: syncDb('isAvailable'),
    getSetting: syncDb('getSetting'),
    setSetting: syncDb('setSetting'),
    getUsers: syncDb('getUsers'),
    getUserById: syncDb('getUserById'),
    isDefaultAdmin: syncDb('isDefaultAdmin'),
    createUser: syncDb('createUser'),
    updateUserRole: syncDb('updateUserRole'),
    deleteUser: syncDb('deleteUser'),
    verifyPassword: syncDb('verifyPassword'),
    updateUserPassword: syncDb('updateUserPassword'),
    generateSalt: syncDb('generateSaltSync'),
    hashPassword: syncDb('pbkdf2HashSync'),
    getProducts: syncDb('getProducts'),
    getProductById: syncDb('getProductById'),
    getProductByBarcode: syncDb('getProductByBarcode'),
    createProduct: syncDb('createProduct'),
    updateProduct: syncDb('updateProduct'),
    deleteProduct: syncDb('deleteProduct'),
    approvisionner: syncDb('approvisionner'),
    getProductsEnAlerte: syncDb('getProductsEnAlerte'),
    getProductsCount: syncDb('getProductsCount'),
    getProductsByType: syncDb('getProductsByType'),
    searchProducts: syncDb('searchProducts'),
    getVentes: syncDb('getVentes'),
    getVenteById: syncDb('getVenteById'),
    getVentesByDate: syncDb('getVentesByDate'),
    getVentesByProduct: syncDb('getVentesByProduct'),
    getVentesByCaissier: syncDb('getVentesByCaissier'),
    createVente: syncDb('createVente'),
    updateProductStock: syncDb('updateProductStock'),
    deleteVente: syncDb('deleteVente'),
    getVentesCount: syncDb('getVentesCount'),
    getDepenses: syncDb('getDepenses'),
    getDepenseById: syncDb('getDepenseById'),
    getDepensesByDate: syncDb('getDepensesByDate'),
    getDepensesByCategorie: syncDb('getDepensesByCategorie'),
    createDepense: syncDb('createDepense'),
    updateDepense: syncDb('updateDepense'),
    deleteDepense: syncDb('deleteDepense'),
    getDepensesTotal: syncDb('getDepensesTotal'),
    getDepensesByCategorieStats: syncDb('getDepensesByCategorieStats'),
    getFournisseurs: syncDb('getFournisseurs'),
    getFournisseurById: syncDb('getFournisseurById'),
    createFournisseur: syncDb('createFournisseur'),
    updateFournisseur: syncDb('updateFournisseur'),
    deleteFournisseur: syncDb('deleteFournisseur'),
    getClients: syncDb('getClients'),
    getClientById: syncDb('getClientById'),
    getClientByTelephone: syncDb('getClientByTelephone'),
    createClient: syncDb('createClient'),
    updateClient: syncDb('updateClient'),
    updateClientStats: syncDb('updateClientStats'),
    deleteClient: syncDb('deleteClient'),
    getClientsCount: syncDb('getClientsCount'),
    searchClients: syncDb('searchClients'),
    getTopClients: syncDb('getTopClients'),
    getReceipts: syncDb('getReceipts'),
    getReceiptById: syncDb('getReceiptById'),
    getReceiptByNumero: syncDb('getReceiptByNumero'),
    getReceiptsByClient: syncDb('getReceiptsByClient'),
    getReceiptsByClientId: syncDb('getReceiptsByClientId'),
    getReceiptsByDate: syncDb('getReceiptsByDate'),
    getReceiptsByCaissier: syncDb('getReceiptsByCaissier'),
    createReceipt: syncDb('createReceipt'),
    getReceiptStats: syncDb('getReceiptStats'),
    getReceiptsCount: syncDb('getReceiptsCount'),
    exportReceipts: syncDb('exportReceipts'),
    verifyReceiptIntegrity: syncDb('verifyReceiptIntegrity'),
    addLog: syncDb('addLog'),
    getLogs: syncDb('getLogs'),
    getLogsByAction: syncDb('getLogsByAction'),
    getLogsByUser: syncDb('getLogsByUser'),
    getLogsByDate: syncDb('getLogsByDate'),
    getLogsCount: syncDb('getLogsCount'),
    clearLogs: syncDb('clearLogs'),
    exportLogs: syncDb('exportLogs'),
    getLoginAttempts: syncDb('getLoginAttempts'),
    setLoginAttempts: syncDb('setLoginAttempts'),
    clearLoginAttempts: syncDb('clearLoginAttempts'),
    isLocked: syncDb('isLocked'),
    getLockRemaining: syncDb('getLockRemaining'),
    getChiffreAffaires: syncDb('getChiffreAffaires'),
    getTotalVentes: syncDb('getTotalVentes'),
    getTopProduits: syncDb('getTopProduits'),
    getVentesParCaissier: syncDb('getVentesParCaissier'),
    getRecettesParMode: syncDb('getRecettesParMode'),
    getMarges: syncDb('getMarges'),
    getMargesByProduct: syncDb('getMargesByProduct'),
    getBeneficeParJour: syncDb('getBeneficeParJour'),
    getBeneficeTotal: syncDb('getBeneficeTotal'),
    getStockValue: syncDb('getStockValue'),
    getStockByType: syncDb('getStockByType'),
    getStockMovements: syncDb('getStockMovements'),
    getDashboardStats: syncDb('getDashboardStats'),
    backup: syncDb('backupDatabase'),
    getDatabaseSize: syncDb('getDatabaseSize'),
    runVacuum: syncDb('runVacuum'),
  },
})
